### ISSUE TITLE
一些地址

### ISSUE THREAD

**Issue by windowsair** [z52c/msgBOOM#1]
一、 http://211.156.201.12:8088/youzheng/ems/security?phone=phonenumber

二、
    1.获取cookies   直接get http://www.icourses.cn/web//sword/portal/user/register/cm/validatePhone
2.发送urllencode phone=18150631931 到 http://www.icourses.cn/web//sword/portal/user/register/cm/beforeSendValidate
3.获取返回的model.data
4.上述值作为uuidtoken
5. 发送 到 http://www.icourses.cn/web//sword/portal/user/register/rg/validateRegisterPicCode    code=7100&uuidToken=8be1dbb12f8e4a6a86c34623e3b9cfb6&phone=18150631931

code 验证码
6.获取验证码 
get http://www.icourses.cn/web//sword/rp?SwordControllerName=getValidateCode&uuidToken=6e33c3cbae3b4d12b1273d25ff9cffd2&rundom=1537780469625

**Comment by dahuoyzs** [comment]
优酷登录短信接口
https://cnpassport.youku.com/newlogin/sms/send.do?appName=youku&fromSite=-2
post格式
fromData参数
phoneCode:86
loginId:【手机号】
countryCode:CN

**Comment by z52c** [comment]
已更新，充气第二个没弄，直接的页面链接也不来一个 @windowsair

**Comment by windowsair** [comment]
> 已更新，充气第二个没弄，直接的页面链接也不来一个 @windowsair

畜生，操作给这么详细了都
